return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "2024.10.31",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 79,
  height = 45,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 12,
  nextobjectid = 203,
  parallaxorigin = {
    x = 1264,
    y = 720
  },
  backgroundcolor = { 39, 185, 154 },
  properties = {},
  tilesets = {
    {
      name = "objs",
      firstgid = 1,
      filename = "../../Tiled/examples/sticker-knight/map/objs.tsx"
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 11,
      name = "static",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 0,
      parallaxy = 0,
      properties = {x = 1},
      objects = {
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 146.97,
          y = 693.727,
          width = 192,
          height = 192,
          rotation = 0,
          gid = 16,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "parallax clouds",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 0.5,
      parallaxy = 0.5,
      properties = {x = 2},
      objects = {
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = -16.2424,
          y = 452.394,
          width = 384,
          height = 128,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 373.939,
          y = 627.121,
          width = 384,
          height = 128,
          rotation = 0,
          gid = 2147483655,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2105.85,
          y = 510.818,
          width = 384,
          height = 128,
          rotation = 0,
          gid = 2147483655,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1453.52,
          y = 651.909,
          width = 384,
          height = 128,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 946.606,
          y = 420.455,
          width = 384,
          height = 128,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 1,
      name = "parallax background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 0.8,
      parallaxy = 0.8,
      properties = {},
      objects = {
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66.6667,
          y = 1079,
          width = 837.333,
          height = 320,
          rotation = 0,
          gid = 59,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 1055,
          width = 920,
          height = 448,
          rotation = 0,
          gid = 59,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1173.54,
          y = 1179.49,
          width = 920,
          height = 352,
          rotation = -10.4469,
          gid = 59,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1824.67,
          y = 1141,
          width = 656.364,
          height = 448,
          rotation = 0,
          gid = 59,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2145.33,
          y = 817,
          width = 129,
          height = 332,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1771.52,
          y = 976.697,
          width = 129,
          height = 332,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 847.515,
          y = 823.788,
          width = 129,
          height = 332,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1440,
          width = 2528,
          height = 385,
          rotation = 0,
          gid = 14,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1087,
          width = 512,
          height = 320,
          rotation = 0,
          gid = 14,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 991,
          width = 256,
          height = 160,
          rotation = 0,
          gid = 62,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 1023,
          width = 256,
          height = 160,
          rotation = 0,
          gid = 62,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 735,
          width = 256,
          height = 160,
          rotation = 0,
          gid = 62,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1087,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 1
          }
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1087,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 1
          }
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 895,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 30,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["floating"] = true,
            ["friction"] = 1
          }
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 1087,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 1
          }
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 1087,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 1
          }
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 1087,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 1
          }
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 1087,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 1
          }
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 1199,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 652,
          y = 1319,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 972,
          y = 1203,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1420,
          y = 1319,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1748,
          y = 1183,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1964.24,
          y = 1354.15,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 1295,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 53,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 1191,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 53,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1048,
          y = 1323,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 53,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1288,
          y = 1211,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 53,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1720,
          y = 1339,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 53,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2008,
          y = 1203,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 53,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2287.76,
          y = 1198.03,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 53,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 514.545,
          y = 907.545,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 53,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 658.667,
          y = 963.606,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 831,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["floating"] = true,
            ["friction"] = 1
          }
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2190.79,
          y = 1361.67,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 53,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "",
          type = "",
          shape = "rectangle",
          x = 786.545,
          y = 919.545,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 53,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 831,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["floating"] = true,
            ["friction"] = 1
          }
        },
        {
          id = 164,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1760,
          y = 1087,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 1
          }
        },
        {
          id = 166,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2016,
          y = 1087,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 1
          }
        },
        {
          id = 175,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 959,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 30,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["floating"] = true,
            ["friction"] = 1
          }
        },
        {
          id = 176,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 1023,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 30,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["floating"] = true,
            ["friction"] = 1
          }
        },
        {
          id = 180,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 671,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 30,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["floating"] = true,
            ["friction"] = 1
          }
        },
        {
          id = 183,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1504,
          y = 1087,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 1
          }
        },
        {
          id = 184,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2272,
          y = 1087,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 1
          }
        },
        {
          id = 187,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 991,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 735,
          width = 128,
          height = 96,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "castle",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 1023,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 959,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 895,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 831,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 639,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 767,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 703,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 575,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1888,
          y = 511,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 575,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 2147483681,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 703,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 2147483681,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 1023,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 2147483681,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 639,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 2147483681,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 895,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 2147483681,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2048,
          y = 511,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 2147483681,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 831,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 2147483681,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 767,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 2147483681,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 959,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 2147483681,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2048,
          y = 447,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 2147483681,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1888,
          y = 447,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2048,
          y = 383,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 2147483681,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1888,
          y = 383,
          width = 256,
          height = 96,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2176,
          y = 223,
          width = 192,
          height = 64,
          rotation = 90,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2240,
          y = 223,
          width = 192,
          height = 64,
          rotation = -270,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2048,
          y = 223,
          width = 192,
          height = 64,
          rotation = 90,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2112,
          y = 223,
          width = 192,
          height = 64,
          rotation = -270,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 223,
          width = 192,
          height = 64,
          rotation = 90,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 223,
          width = 192,
          height = 64,
          rotation = -270,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 415,
          width = 192,
          height = 64,
          rotation = -90,
          gid = 29,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "castledeco",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2063,
          y = 698,
          width = 65,
          height = 64,
          rotation = 0,
          gid = 55,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2063,
          y = 557,
          width = 65,
          height = 64,
          rotation = 0,
          gid = 55,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "exit",
          shape = "rectangle",
          x = 2016,
          y = 991,
          width = 160,
          height = 192,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {
            ["map"] = "scene/game/map/sandbox2.json"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "shading",
      class = "",
      visible = true,
      opacity = 0.36,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 991,
          width = 32,
          height = 512,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 991,
          width = 32,
          height = 256,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 991,
          width = 32,
          height = 256,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2208,
          y = 991,
          width = 32,
          height = 512,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1888,
          y = 479,
          width = 32,
          height = 64,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2272,
          y = 479,
          width = 32,
          height = 64,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 490,
          width = 254,
          height = 11,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2272,
          y = 415,
          width = 32,
          height = 64,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1888,
          y = 415,
          width = 32,
          height = 188,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2272,
          y = 351,
          width = 32,
          height = 128,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1888,
          y = 351,
          width = 32,
          height = 64,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 991,
          width = 32,
          height = 192,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 735,
          width = 32,
          height = 160,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 735,
          width = 32,
          height = 160,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 991,
          width = 32,
          height = 128,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2496,
          y = 1440,
          width = 32,
          height = 448,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1440,
          width = 32,
          height = 448,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "game",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 58,
          name = "hero",
          type = "",
          shape = "rectangle",
          x = 45,
          y = 979.5,
          width = 128,
          height = 160,
          rotation = 0,
          gid = 22,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "block",
          type = "",
          shape = "rectangle",
          x = 594,
          y = 571,
          width = 96,
          height = 96,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {
            ["bodyType"] = "dynamic",
            ["density"] = 2,
            ["friction"] = 0.45
          }
        },
        {
          id = 182,
          name = "block",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 799,
          width = 96,
          height = 96,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {
            ["bodyType"] = "dynamic",
            ["density"] = 2,
            ["friction"] = 0.45
          }
        },
        {
          id = 190,
          name = "",
          type = "",
          shape = "rectangle",
          x = 238,
          y = 947.5,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 17,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 860.5,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 17,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "",
          type = "",
          shape = "rectangle",
          x = 481,
          y = 950.5,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 17,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1583.45,
          y = 829.318,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 17,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1826.45,
          y = 832.318,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 17,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1697.45,
          y = 742.318,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 17,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "above",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 481,
          y = 997,
          width = 224,
          height = 32,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "bounds",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 197,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2496,
          y = 0,
          width = 32,
          height = 992,
          rotation = 0,
          visible = true,
          properties = {
            ["bodyType"] = "static"
          }
        },
        {
          id = 195,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 32,
          height = 992,
          rotation = 0,
          visible = true,
          properties = {
            ["bodyType"] = "static"
          }
        }
      }
    }
  }
}
